import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

option_as_alt = "Both"

[font]
size = 24

[font.bold]
family = "LiterationMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "LiterationMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "LiterationMono Nerd Font"
style = "Italic"

[font.normal]
family = "LiterationMono Nerd Font"
style = "Regular"
